---
#- name: Install specific version of Docker Engine
#  ansible.builtin.apt:
#    name:
#      - "docker-ce={{ version }}~{{ ansible_distribution | lower  }}.{{ ansible_distribution_version }}~{{ ansible_distribution_release | lower }}"
#      - "docker-ce-cli={{ version }}~{{ ansible_distribution | lower  }}.{{ ansible_distribution_version }}~{{ ansible_distribution_release | lower }}"
#      - "containerd.io"
#    state: present
#    update_cache: yes
- name: Set docker package version string
  set_fact:
    docker_package_version: >-
      {{ version }}~{{ ansible_distribution | lower }}{% if ansible_distribution == "Debian" %}.{{ ansible_distribution_version.split('.')[0] }}{% else %}.{{ ansible_distribution_version }}{% endif %}~{{ ansible_distribution_release | lower }}

- name: Install specific version of Docker Engine
  ansible.builtin.apt:
    name:
      - "docker-ce={{ docker_package_version }}"
      - "docker-ce-cli={{ docker_package_version }}"
      - "containerd.io"
    state: present
    update_cache: yes

- name: Ensure Docker service is running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true